util-vserver-0.30.208

diff --git a/scripts/vsysvwrapper b/scripts/vsysvwrapper
--- a/scripts/vsysvwrapper
+++ b/scripts/vsysvwrapper
@@ -18,15 +18,16 @@
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 
 # Helper script for all the v_xxx scripts
-: ${UTIL_VSERVER_VARS:=$(dirname $0)/util-vserver-vars}
+: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
 test -e "$UTIL_VSERVER_VARS" || {
-    echo "Can not find util-vserver installation; aborting..."
+    echo $"Can not find util-vserver installation (the file '$UTIL_VSERVER_VARS' would be expected); aborting..." >&2
     exit 1
 }
 . "$UTIL_VSERVER_VARS"
 
 if [ $# = 0 ] ; then
 	echo vsysvwrapper service_name >&2
+	exit 6
 else
 	SERVICE=$1
 	shift
@@ -39,8 +40,6 @@ else
 	do
 		IPOPT="$IPOPT --ip $oneip"
 	done
-	echo exec $SBINDIR/chbind $IPOPT /etc/init.d/$SERVICE $*
-	exec $SBINDIR/chbind $IPOPT /etc/init.d/$SERVICE $*
+	echo exec $CHBIND $IPOPT /etc/init.d/$SERVICE "$@"
+	exec $CHBIND $IPOPT /etc/init.d/$SERVICE "$@"
 fi
-
-
